dist: trusty

sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

script:
  - gradle clean build check envStart integrationTest envStop

after_success:
  - bash <(curl -s https://codecov.io/bash)
