dist: trusty

sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

script:
  - gradle clean assemble envStart check envStop -Ptest.mode=local

after_success:
  - bash <(curl -s https://codecov.io/bash)

