dist: trusty

language: java

jdk:
  - oraclejdk8
  - openjdk8

before_script:
  - cp application/config.properties.example application/config.properties

script:
  - gradle clean build check

after_success:
  - bash <(curl -s https://codecov.io/bash)
